model: VISRANK
seed: 2020

method: average_top_k   
top_num: 1

use_modality: False
log_wandb: False
wandb_project: 'REC'
show_progress: False
checkpoint_dir: 'saved'

MAX_ITEM_LIST_LENGTH: 10

data_path: ../dataset/
dataset: Pixel200K

v_feat_path: ../dataset/visual_features/RN50.npy


# training settings
epochs: 1
need_training: False
train_batch_size: 512  
optim_args: {
  learning_rate: 0.0001,
  weight_decay: 0.1  
}

# eval settings
eval_batch_size: 1
topk: [5,10]
metrics: ['Recall', 'NDCG']
valid_metric: NDCG@10
metric_decimal_place: 7
eval_step: 1 
stopping_step: 30


